ZEN-32774 bump urllib3 1.24->1.24.3
zenoss/zenoss-py-deps pull request #72
Opened 2020-11-12 13:47 UTC by romanbakaleyko

2020-11-12 13:51 UTC, webhookbotuser commented
Can one of the admins verify this patch?

2020-11-12 17:50 UTC, jpeacock-zenoss requested changes

2020-11-12 17:50 UTC, jpeacock-zenoss commented on requirements_3rd.txt
> +httplib2==0.18.1
I thought you were not going to upgrade this library.

I did a simple grep over the code we use and I found these packages referencing "httplib2":
* zenoss-protocols
* modelindex
* ZenPacks.zenoss.OpenStack
* eventlet
* mechanize
* pip
* pyrabbit

2020-11-13 14:16 UTC, jpeacock-zenoss approved these changes

2020-11-13 15:35 UTC, merged